### ISSUE TITLE
Fetch models not working when running in colab with gdrive mapped

### ISSUE THREAD

**Issue by gbtota** [Luxadevi/Ollama-Companion#7]
Fetch models not working when running in colab with google drive mapped.

downloading works the models get downloaded into the llama on the gdrive folder but fetch models button does nothing no models show up even tho they are clearly in the folder.

My guess is the because google drive has a space in the path "My Drive"

**Comment by Luxadevi** [comment]
Heya,

So if I understand correctly you have added a Google drive storage component and are downloading the models to this drive right? Did you also configure Ollama so it would read out of this added mount/directory? 
These models are downloaded with ollama modelfile creator page or a ollama pull command? 

Let me know if you got it working lately, if it did not work I would suggest to use a symbolic link for this folder and hard mount this to the .ollama/ directory where the models are stored usually.

**Comment by Luxadevi** [comment]
I'll close this issue for now, if you have different questions feel free to reopen this issue.
