### ISSUE TITLE
No support for exl2 models ? 

### ISSUE THREAD

**Issue by gbtota** [Luxadevi/Ollama-Companion#8]
great project but can you add support for these ? 

turboderp/Mistral-7B-OpenOrca-exl2](https://huggingface.co/turboderp/Mistral-7B-OpenOrca-exl2

**Comment by Luxadevi** [comment]
For now Ollama doesn't support EXL2 but I dropped the question there if it they are interested in using or supporting EXL2 file formats in the future. The best way would be to add it to ollama natively so everyone can enjoy using EXL2 models.
But it's up to them if they deem it within the scope of Ollama.

Right now I'm mostly focused on building a LLM stack with this project that supports Ollama and  apps that work/integrate with it.
I would like to add lanchain and vector databases to this stack and maybe try adding some sort of interactive autogen/agent-framework.

But ollama is the base of the stack right now and don't want to add different inference stacks.

But feel free to add something yourself to this ongoing project.

If you would like to use Exl2 and other file formats I would suggest using a allround app like textgen-ui.

Also if you want a certain model working with ollama from huggingface for example, this companion has build in quantization like The Bloke uses so you can quantize almost all models you encounter. (transformers, pytorch)

**Comment by Luxadevi** [comment]
I'll close this issue for now, if you have different questions feel free to reopen this issue.
